# Generated by Django 4.2.1 on 2023-05-29 12:35

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='RecordModel',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255)),
                ('abstract', models.TextField()),
                ('psed_classification_id', models.IntegerField(max_length=11)),
                ('for_commercialization', models.IntegerField(max_length=1)),
                ('date_uploaded', models.DateTimeField()),
            ],
        ),
    ]
